// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrplqxtwporuulgazizx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycGxxeHR3cG9ydXVsZ2F6aXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NTc5MjUsImV4cCI6MjA1ODQzMzkyNX0.chIcV8_Uq-4-kb4NdolZZ1bG0mTEXgM2X70sVSLXgvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);